services:
  - type: web
    name: ranjit-tour-travels-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
